// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.1
// source: order.proto

package order_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Common Order message used in responses
type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	OrderAddress  string                 `protobuf:"bytes,4,opt,name=order_address,json=orderAddress,proto3" json:"order_address,omitempty"`
	OrderLocation string                 `protobuf:"bytes,5,opt,name=order_location,json=orderLocation,proto3" json:"order_location,omitempty"`
	OrderDate     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=order_date,json=orderDate,proto3" json:"order_date,omitempty"`
	OrderTimeGap  *durationpb.Duration   `protobuf:"bytes,7,opt,name=order_time_gap,json=orderTimeGap,proto3" json:"order_time_gap,omitempty"`
	OrderStatus   string                 `protobuf:"bytes,8,opt,name=order_status,json=orderStatus,proto3" json:"order_status,omitempty"` // "pending", "active", "finished", "cancelled"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{0}
}

func (x *Order) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *Order) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Order) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Order) GetOrderAddress() string {
	if x != nil {
		return x.OrderAddress
	}
	return ""
}

func (x *Order) GetOrderLocation() string {
	if x != nil {
		return x.OrderLocation
	}
	return ""
}

func (x *Order) GetOrderDate() *timestamppb.Timestamp {
	if x != nil {
		return x.OrderDate
	}
	return nil
}

func (x *Order) GetOrderTimeGap() *durationpb.Duration {
	if x != nil {
		return x.OrderTimeGap
	}
	return nil
}

func (x *Order) GetOrderStatus() string {
	if x != nil {
		return x.OrderStatus
	}
	return ""
}

type CreateOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrderAddress  string                 `protobuf:"bytes,2,opt,name=order_address,json=orderAddress,proto3" json:"order_address,omitempty"`    //адрес(или координаты)
	OrderLocation string                 `protobuf:"bytes,3,opt,name=order_location,json=orderLocation,proto3" json:"order_location,omitempty"` //место или заведение
	OrderDate     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=order_date,json=orderDate,proto3" json:"order_date,omitempty"`
	OrderTimeGap  *durationpb.Duration   `protobuf:"bytes,5,opt,name=order_time_gap,json=orderTimeGap,proto3" json:"order_time_gap,omitempty"` //time gap to go to the location
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{1}
}

func (x *CreateOrderRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateOrderRequest) GetOrderAddress() string {
	if x != nil {
		return x.OrderAddress
	}
	return ""
}

func (x *CreateOrderRequest) GetOrderLocation() string {
	if x != nil {
		return x.OrderLocation
	}
	return ""
}

func (x *CreateOrderRequest) GetOrderDate() *timestamppb.Timestamp {
	if x != nil {
		return x.OrderDate
	}
	return nil
}

func (x *CreateOrderRequest) GetOrderTimeGap() *durationpb.Duration {
	if x != nil {
		return x.OrderTimeGap
	}
	return nil
}

type CreateOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderResponse) Reset() {
	*x = CreateOrderResponse{}
	mi := &file_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResponse) ProtoMessage() {}

func (x *CreateOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResponse.ProtoReflect.Descriptor instead.
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{2}
}

func (x *CreateOrderResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetUserOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserOrdersRequest) Reset() {
	*x = GetUserOrdersRequest{}
	mi := &file_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserOrdersRequest) ProtoMessage() {}

func (x *GetUserOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserOrdersRequest.ProtoReflect.Descriptor instead.
func (*GetUserOrdersRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserOrdersRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserOrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*Order               `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserOrdersResponse) Reset() {
	*x = GetUserOrdersResponse{}
	mi := &file_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserOrdersResponse) ProtoMessage() {}

func (x *GetUserOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserOrdersResponse.ProtoReflect.Descriptor instead.
func (*GetUserOrdersResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserOrdersResponse) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

type GetAvailableOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAvailableOrdersRequest) Reset() {
	*x = GetAvailableOrdersRequest{}
	mi := &file_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvailableOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailableOrdersRequest) ProtoMessage() {}

func (x *GetAvailableOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailableOrdersRequest.ProtoReflect.Descriptor instead.
func (*GetAvailableOrdersRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{5}
}

func (x *GetAvailableOrdersRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetAvailableOrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*Order               `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAvailableOrdersResponse) Reset() {
	*x = GetAvailableOrdersResponse{}
	mi := &file_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvailableOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailableOrdersResponse) ProtoMessage() {}

func (x *GetAvailableOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailableOrdersResponse.ProtoReflect.Descriptor instead.
func (*GetAvailableOrdersResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{6}
}

func (x *GetAvailableOrdersResponse) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

type GetOrderByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderByIdRequest) Reset() {
	*x = GetOrderByIdRequest{}
	mi := &file_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderByIdRequest) ProtoMessage() {}

func (x *GetOrderByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderByIdRequest.ProtoReflect.Descriptor instead.
func (*GetOrderByIdRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{7}
}

func (x *GetOrderByIdRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type GetOrderByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderByIdResponse) Reset() {
	*x = GetOrderByIdResponse{}
	mi := &file_order_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderByIdResponse) ProtoMessage() {}

func (x *GetOrderByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderByIdResponse.ProtoReflect.Descriptor instead.
func (*GetOrderByIdResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{8}
}

func (x *GetOrderByIdResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type CancelOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"` // string reason = 2; // Optional reason for cancellation
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderRequest) Reset() {
	*x = CancelOrderRequest{}
	mi := &file_order_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderRequest) ProtoMessage() {}

func (x *CancelOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderRequest.ProtoReflect.Descriptor instead.
func (*CancelOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{9}
}

func (x *CancelOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type CancelOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderResponse) Reset() {
	*x = CancelOrderResponse{}
	mi := &file_order_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderResponse) ProtoMessage() {}

func (x *CancelOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderResponse.ProtoReflect.Descriptor instead.
func (*CancelOrderResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{10}
}

func (x *CancelOrderResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CompleteOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteOrderRequest) Reset() {
	*x = CompleteOrderRequest{}
	mi := &file_order_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteOrderRequest) ProtoMessage() {}

func (x *CompleteOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteOrderRequest.ProtoReflect.Descriptor instead.
func (*CompleteOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{11}
}

func (x *CompleteOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type CompleteOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteOrderResponse) Reset() {
	*x = CompleteOrderResponse{}
	mi := &file_order_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteOrderResponse) ProtoMessage() {}

func (x *CompleteOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteOrderResponse.ProtoReflect.Descriptor instead.
func (*CompleteOrderResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{12}
}

func (x *CompleteOrderResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_order_proto protoreflect.FileDescriptor

const file_order_proto_rawDesc = "" +
	"\n" +
	"\vorder.proto\x12\rorder_service\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"\xc1\x02\n" +
	"\x05Order\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\x12#\n" +
	"\rorder_address\x18\x04 \x01(\tR\forderAddress\x12%\n" +
	"\x0eorder_location\x18\x05 \x01(\tR\rorderLocation\x129\n" +
	"\n" +
	"order_date\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\torderDate\x12?\n" +
	"\x0eorder_time_gap\x18\a \x01(\v2\x19.google.protobuf.DurationR\forderTimeGap\x12!\n" +
	"\forder_status\x18\b \x01(\tR\vorderStatus\"\xf5\x01\n" +
	"\x12CreateOrderRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12#\n" +
	"\rorder_address\x18\x02 \x01(\tR\forderAddress\x12%\n" +
	"\x0eorder_location\x18\x03 \x01(\tR\rorderLocation\x129\n" +
	"\n" +
	"order_date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\torderDate\x12?\n" +
	"\x0eorder_time_gap\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\forderTimeGap\"/\n" +
	"\x13CreateOrderResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"/\n" +
	"\x14GetUserOrdersRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"E\n" +
	"\x15GetUserOrdersResponse\x12,\n" +
	"\x06orders\x18\x01 \x03(\v2\x14.order_service.OrderR\x06orders\"3\n" +
	"\x19GetAvailableOrdersRequest\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"J\n" +
	"\x1aGetAvailableOrdersResponse\x12,\n" +
	"\x06orders\x18\x01 \x03(\v2\x14.order_service.OrderR\x06orders\"0\n" +
	"\x13GetOrderByIdRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"B\n" +
	"\x14GetOrderByIdResponse\x12*\n" +
	"\x05order\x18\x01 \x01(\v2\x14.order_service.OrderR\x05order\"/\n" +
	"\x12CancelOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"/\n" +
	"\x13CancelOrderResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"1\n" +
	"\x14CompleteOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"1\n" +
	"\x15CompleteOrderResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xc2\x04\n" +
	"\fOrderService\x12V\n" +
	"\vCreateOrder\x12!.order_service.CreateOrderRequest\x1a\".order_service.CreateOrderResponse\"\x00\x12\\\n" +
	"\rGetUserOrders\x12#.order_service.GetUserOrdersRequest\x1a$.order_service.GetUserOrdersResponse\"\x00\x12k\n" +
	"\x12GetAvailableOrders\x12(.order_service.GetAvailableOrdersRequest\x1a).order_service.GetAvailableOrdersResponse\"\x00\x12Y\n" +
	"\fGetOrderById\x12\".order_service.GetOrderByIdRequest\x1a#.order_service.GetOrderByIdResponse\"\x00\x12V\n" +
	"\vCancelOrder\x12!.order_service.CancelOrderRequest\x1a\".order_service.CancelOrderResponse\"\x00\x12\\\n" +
	"\rCompleteOrder\x12#.order_service.CompleteOrderRequest\x1a$.order_service.CompleteOrderResponse\"\x00B#Z!order_service/proto/order_serviceb\x06proto3"

var (
	file_order_proto_rawDescOnce sync.Once
	file_order_proto_rawDescData []byte
)

func file_order_proto_rawDescGZIP() []byte {
	file_order_proto_rawDescOnce.Do(func() {
		file_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)))
	})
	return file_order_proto_rawDescData
}

var file_order_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_order_proto_goTypes = []any{
	(*Order)(nil),                      // 0: order_service.Order
	(*CreateOrderRequest)(nil),         // 1: order_service.CreateOrderRequest
	(*CreateOrderResponse)(nil),        // 2: order_service.CreateOrderResponse
	(*GetUserOrdersRequest)(nil),       // 3: order_service.GetUserOrdersRequest
	(*GetUserOrdersResponse)(nil),      // 4: order_service.GetUserOrdersResponse
	(*GetAvailableOrdersRequest)(nil),  // 5: order_service.GetAvailableOrdersRequest
	(*GetAvailableOrdersResponse)(nil), // 6: order_service.GetAvailableOrdersResponse
	(*GetOrderByIdRequest)(nil),        // 7: order_service.GetOrderByIdRequest
	(*GetOrderByIdResponse)(nil),       // 8: order_service.GetOrderByIdResponse
	(*CancelOrderRequest)(nil),         // 9: order_service.CancelOrderRequest
	(*CancelOrderResponse)(nil),        // 10: order_service.CancelOrderResponse
	(*CompleteOrderRequest)(nil),       // 11: order_service.CompleteOrderRequest
	(*CompleteOrderResponse)(nil),      // 12: order_service.CompleteOrderResponse
	(*timestamppb.Timestamp)(nil),      // 13: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),        // 14: google.protobuf.Duration
}
var file_order_proto_depIdxs = []int32{
	13, // 0: order_service.Order.order_date:type_name -> google.protobuf.Timestamp
	14, // 1: order_service.Order.order_time_gap:type_name -> google.protobuf.Duration
	13, // 2: order_service.CreateOrderRequest.order_date:type_name -> google.protobuf.Timestamp
	14, // 3: order_service.CreateOrderRequest.order_time_gap:type_name -> google.protobuf.Duration
	0,  // 4: order_service.GetUserOrdersResponse.orders:type_name -> order_service.Order
	0,  // 5: order_service.GetAvailableOrdersResponse.orders:type_name -> order_service.Order
	0,  // 6: order_service.GetOrderByIdResponse.order:type_name -> order_service.Order
	1,  // 7: order_service.OrderService.CreateOrder:input_type -> order_service.CreateOrderRequest
	3,  // 8: order_service.OrderService.GetUserOrders:input_type -> order_service.GetUserOrdersRequest
	5,  // 9: order_service.OrderService.GetAvailableOrders:input_type -> order_service.GetAvailableOrdersRequest
	7,  // 10: order_service.OrderService.GetOrderById:input_type -> order_service.GetOrderByIdRequest
	9,  // 11: order_service.OrderService.CancelOrder:input_type -> order_service.CancelOrderRequest
	11, // 12: order_service.OrderService.CompleteOrder:input_type -> order_service.CompleteOrderRequest
	2,  // 13: order_service.OrderService.CreateOrder:output_type -> order_service.CreateOrderResponse
	4,  // 14: order_service.OrderService.GetUserOrders:output_type -> order_service.GetUserOrdersResponse
	6,  // 15: order_service.OrderService.GetAvailableOrders:output_type -> order_service.GetAvailableOrdersResponse
	8,  // 16: order_service.OrderService.GetOrderById:output_type -> order_service.GetOrderByIdResponse
	10, // 17: order_service.OrderService.CancelOrder:output_type -> order_service.CancelOrderResponse
	12, // 18: order_service.OrderService.CompleteOrder:output_type -> order_service.CompleteOrderResponse
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_order_proto_init() }
func file_order_proto_init() {
	if File_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_proto_goTypes,
		DependencyIndexes: file_order_proto_depIdxs,
		MessageInfos:      file_order_proto_msgTypes,
	}.Build()
	File_order_proto = out.File
	file_order_proto_goTypes = nil
	file_order_proto_depIdxs = nil
}
