version: '3'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=orderqapp
    volumes:
      - ./views:/app/views
      - ./static:/app/static
      - ./conf:/app/conf
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=orderqapp
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 