version: '3'

services:
  auth_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth_service
    env_file:
      - .env
    ports:
      - "9000:9000"
    depends_on:
      - postgres
    networks:
      - auth_network

  postgres:
    image: postgres:15-alpine
    container_name: auth_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auth_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - auth_network

networks:
  auth_network:
    driver: bridge

volumes:
  postgres_data: