version: '3'

tasks:

  generate-proto:
    desc: Генерация Go-кода из .proto файлов
    cmds:
      - |
        protoc --proto_path=proto/ \
               --go_out=paths=source_relative:proto/notification_service \
               --go-grpc_out=paths=source_relative:proto/notification_service \
               --grpc-gateway_out=paths=source_relative:proto/notification_service \
               --go-grpc_opt=require_unimplemented_servers=false \
               --grpc-gateway_opt=logtostderr=true \
               $(find proto/ -name "*.proto")
    deps:
      - install-proto-plugins

  install-proto-plugins:
    desc: Установка плагинов protoc для Go
    cmds:
      - go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
      - go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
      - go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@latest
    silent: true